apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appflowy-worker.fullname" . }}
  labels:
    {{- include "appflowy-worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "appflowy-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "appflowy-worker.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APPFLOWY_WORKER_REDIS_URL
              value: {{ .Values.global.redis.uri }}
            - name: APPFLOWY_WORKER_ENVIRONMENT
              value: production
            - name: APPFLOWY_WORKER_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret.name }}
                  key: {{ .Values.global.secret.postgres.appflowy.databaseUrl.key }}
            - name: APPFLOWY_WORKER_IMPORT_TICK_INTERVAL
              value: {{ .Values.importTickInterval | quote}}
            - name: APPFLOWY_S3_USE_MINIO
              value: {{ .Values.global.s3.useMinio | quote }}
            - name: APPFLOWY_S3_MINIO_URL
              value: {{ .Values.global.s3.minioUrl }}
            - name: APPFLOWY_S3_ACCESS_KEY
              value: {{ .Values.global.s3.accessKey }}
            - name: APPFLOWY_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret.name }}
                  key: {{ .Values.global.secret.s3.secret.key }}
            - name: APPFLOWY_S3_BUCKET
              value: {{ .Values.global.s3.bucket }}
            - name: APPFLOWY_S3_REGION
              value: {{ .Values.global.s3.region }}
            - name: APPFLOWY_MAILER_SMTP_HOST
              value: {{ .Values.global.smtp.host }}
            - name: APPFLOWY_MAILER_SMTP_PORT
              value: {{ .Values.global.smtp.port | quote}}
            - name: APPFLOWY_MAILER_SMTP_USERNAME
              value: {{ .Values.global.smtp.user }}
            - name: APPFLOWY_MAILER_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret.name }}
                  key: {{ .Values.global.secret.smtp.password.key }}
            - name: APPFLOWY_INDEXER_ENABLED
              value: {{ if .Values.global.ai.enabled }}{{ .Values.indexer.enabled | quote }}{{ else }}"false"{{ end }}
            {{- if .Values.global.ai.enabled }}
            - name: APPFLOWY_AI_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret.name }}
                  key: {{ .Values.global.secret.ai.openAIAPIKey.key }}
            {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
