{{- if .Values.global.ingress.traefik.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "appflowy-gotrue.fullname" . }}
spec:
  entryPoints:
    - {{ if eq .Values.global.scheme "https" }}{{ .Values.global.ingress.traefik.secureEntryPoint }}{{ else }}{{ .Values.global.ingress.traefik.entryPoint }}{{ end }}
  routes:
    - match: Host(`{{ .Values.global.externalHost }}`) && PathPrefix(`/gotrue`)
      kind: Rule
      services:
        - name: {{ include "appflowy-gotrue.fullname" . }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: {{ include "appflowy-gotrue.fullname" . }}-stripprefix
        {{- with .Values.global.ingress.traefik.extraMiddlewares }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
  {{- with .Values.global.ingress.traefik.tlsSecretName }}
  tls:
    secretName: {{ . }}
  {{- end }}
{{- end }}
